var mongoose =require('mongoose');

var employee= mongoose.model('employee',new mongoose.Schema({
    employeeId:{
        type:String,
        maxlength:30,
        minlength:1,
        required:true,
        unique:true
    },
    firstName:{
        type:String,
        maxlength:30,
        minlength:1,
        required:true
    },
    lastName:{
        type:String,
        maxlength:30,
        minlength:1,
        required:true
    },
    dob:{
        type:Date,
        required:true
    },
    email:{
        type:String,
        minlength:6,
        unique:true,
        required:true
    },
    password:{
        type:String,
        hide:true,
        minlength:8,
        required:true
    },
    confPassword:{
        type:String,
        hide:true,
        minlength:8,
        required:true
    },
    role:{
        type:String,
        required:true
    },
    team:{
        type:String,
        required:true
    },
    salary:{
        type:Number,
        required:true
    }
})
);

module.exports=employee;