const mongoose =require('mongoose');

const newUser= mongoose.model('newUser',new mongoose.Schema({
    employeeId:{
        type:String,
        maxlength:30,
        required:true,
        unique:true
    },
    firstName:{
        type:String,
        maxlength:30,
        required:true
    },
    dob:{
        type:Date,
        required:true
    },
    lastName:{
        type:String,
        maxlength:30,
        required:true
    },
    email:{
        type:String,
        minlength:6,
        unique:true,
        required:true
    },
    password:{
        type:String,
        hide:true,
        minlength:8,
        required:true
    },
    confPassword:{
        type:String,
        hide:true,
        minlength:8,
        required:true
    },
    role:{
        type:String,
        required:true
    }
})
);

module.exports=newUser;